import type { ActivityEvent, Agent } from "./types";

/**
 * Demonstration register for a fictional customer, Northwind Group.
 *
 * Every screen reads from this one source so the views always agree with each
 * other. Replace this module with the real ingestion layer; nothing else in the
 * app reaches for agent data directly.
 */
export const ORGANISATION = "Northwind Group";

export const AGENTS: readonly Agent[] = [
  {
    id: "procurement-assistant",
    name: "Procurement Assistant",
    department: "Finance",
    owner: "J. Miles",
    inServiceSince: "Mar 2026",
    accessExpires: null,
    autonomy: "threshold",
    canMoveMoney: true,
    access: [
      { name: "Supplier database", mode: "read" },
      { name: "Supplier email", mode: "write" },
      { name: "SAP Ariba", mode: "irreversible" },
      { name: "Corporate card", mode: "irreversible" },
    ],
    tools: [
      { name: "read_inbox", mode: "read" },
      { name: "send_email", mode: "write" },
      { name: "place_order", mode: "irreversible" },
      { name: "approve_invoice", mode: "irreversible" },
    ],
    authority: 88,
    oversight: 22,
    posture: { ASI01: 23, ASI02: 31, ASI03: 35, ASI04: 62, ASI05: 80, ASI06: 40, ASI07: 70, ASI08: 38, ASI09: 25, ASI10: 44 },
  },
  {
    id: "dev-assistant",
    name: "Dev Assistant",
    department: "Engineering",
    owner: "R. Okafor",
    inServiceSince: "Jan 2026",
    accessExpires: "Dec 2026",
    autonomy: "threshold",
    canMoveMoney: false,
    access: [
      { name: "Source code", mode: "read" },
      { name: "GitHub org", mode: "write" },
      { name: "CI runners", mode: "irreversible" },
      { name: "Staging AWS", mode: "irreversible" },
    ],
    tools: [
      { name: "read_repo", mode: "read" },
      { name: "write_code", mode: "write" },
      { name: "open_pr", mode: "write" },
      { name: "run_shell", mode: "irreversible" },
    ],
    authority: 61,
    oversight: 70,
    posture: { ASI01: 62, ASI02: 55, ASI03: 60, ASI04: 48, ASI05: 38, ASI06: 72, ASI07: 75, ASI08: 52, ASI09: 58, ASI10: 66 },
  },
  {
    id: "reporting-analyst",
    name: "Reporting Analyst",
    department: "Finance",
    owner: "S. Vale",
    inServiceSince: "Nov 2025",
    accessExpires: "Nov 2026",
    autonomy: "full-approval",
    canMoveMoney: false,
    access: [
      { name: "Data warehouse", mode: "read" },
      { name: "BI workspace", mode: "write" },
    ],
    tools: [
      { name: "run_query", mode: "read" },
      { name: "build_chart", mode: "write" },
    ],
    authority: 24,
    oversight: 92,
    posture: { ASI01: 82, ASI02: 90, ASI03: 88, ASI04: 80, ASI05: 92, ASI06: 84, ASI07: 88, ASI08: 90, ASI09: 86, ASI10: 88 },
  },
  {
    id: "customer-support-bot",
    name: "Customer Support Bot",
    department: "Operations",
    owner: "H. Nair",
    inServiceSince: "Sep 2025",
    accessExpires: null,
    autonomy: "none",
    canMoveMoney: true,
    access: [
      { name: "Customer records", mode: "read" },
      { name: "Zendesk", mode: "write" },
      { name: "Refund API", mode: "irreversible" },
    ],
    tools: [
      { name: "read_customer", mode: "read" },
      { name: "send_reply", mode: "write" },
      { name: "update_ticket", mode: "write" },
      { name: "issue_refund", mode: "irreversible" },
    ],
    authority: 72,
    oversight: 34,
    posture: { ASI01: 28, ASI02: 44, ASI03: 48, ASI04: 66, ASI05: 78, ASI06: 36, ASI07: 74, ASI08: 45, ASI09: 30, ASI10: 40 },
  },
  {
    id: "hr-intake-agent",
    name: "HR Intake Agent",
    department: "People",
    owner: "M. Duarte",
    inServiceSince: "Feb 2026",
    accessExpires: "Feb 2027",
    autonomy: "threshold",
    canMoveMoney: false,
    access: [
      { name: "Workday", mode: "read" },
      { name: "Candidate inbox", mode: "read" },
      { name: "Interview calendar", mode: "write" },
    ],
    tools: [
      { name: "read_cv", mode: "read" },
      { name: "schedule_interview", mode: "write" },
      { name: "send_email", mode: "write" },
    ],
    authority: 33,
    oversight: 78,
    posture: { ASI01: 68, ASI02: 82, ASI03: 76, ASI04: 74, ASI05: 88, ASI06: 62, ASI07: 84, ASI08: 80, ASI09: 72, ASI10: 78 },
  },
  {
    id: "scheduler",
    name: "Scheduler",
    department: "Operations",
    owner: "H. Nair",
    inServiceSince: "Aug 2025",
    accessExpires: "Aug 2026",
    autonomy: "none",
    canMoveMoney: false,
    access: [
      { name: "Directory", mode: "read" },
      { name: "Calendar", mode: "write" },
      { name: "Meeting rooms", mode: "write" },
    ],
    tools: [
      { name: "book_slot", mode: "write" },
      { name: "send_invite", mode: "write" },
    ],
    authority: 21,
    oversight: 66,
    posture: { ASI01: 76, ASI02: 86, ASI03: 70, ASI04: 76, ASI05: 90, ASI06: 74, ASI07: 80, ASI08: 86, ASI09: 80, ASI10: 82 },
  },
  {
    id: "contract-reviewer",
    name: "Contract Reviewer",
    department: "Legal",
    owner: "P. Achterberg",
    inServiceSince: "Apr 2026",
    accessExpires: null,
    autonomy: "threshold",
    canMoveMoney: false,
    access: [
      { name: "Contract store", mode: "read" },
      { name: "Clause library", mode: "read" },
      { name: "DocuSign drafts", mode: "write" },
    ],
    tools: [
      { name: "read_contract", mode: "read" },
      { name: "flag_risk", mode: "read" },
      { name: "draft_clause", mode: "write" },
    ],
    authority: 47,
    oversight: 74,
    posture: { ASI01: 51, ASI02: 78, ASI03: 66, ASI04: 70, ASI05: 84, ASI06: 46, ASI07: 82, ASI08: 76, ASI09: 44, ASI10: 64 },
  },
  {
    id: "campaign-writer",
    name: "Campaign Writer",
    department: "Marketing",
    owner: "L. Ferreira",
    inServiceSince: "Jun 2026",
    accessExpires: "Jun 2027",
    autonomy: "threshold",
    canMoveMoney: true,
    access: [
      { name: "Brand assets", mode: "read" },
      { name: "Analytics", mode: "read" },
      { name: "CMS", mode: "write" },
      { name: "Ad platform", mode: "irreversible" },
    ],
    tools: [
      { name: "read_analytics", mode: "read" },
      { name: "publish_post", mode: "write" },
      { name: "set_ad_budget", mode: "irreversible" },
    ],
    authority: 58,
    oversight: 52,
    posture: { ASI01: 51, ASI02: 60, ASI03: 64, ASI04: 72, ASI05: 86, ASI06: 58, ASI07: 78, ASI08: 70, ASI09: 50, ASI10: 62 },
  },
  {
    id: "it-provisioning-agent",
    name: "IT Provisioning Agent",
    department: "Engineering",
    owner: "R. Okafor",
    inServiceSince: "Oct 2025",
    accessExpires: null,
    autonomy: "none",
    canMoveMoney: false,
    access: [
      { name: "HR directory", mode: "read" },
      { name: "Licence pool", mode: "write" },
      { name: "Entra ID", mode: "irreversible" },
      { name: "Device fleet", mode: "irreversible" },
    ],
    tools: [
      { name: "reset_password", mode: "write" },
      { name: "create_account", mode: "irreversible" },
      { name: "grant_role", mode: "irreversible" },
      { name: "revoke_access", mode: "irreversible" },
    ],
    authority: 94,
    oversight: 28,
    posture: { ASI01: 22, ASI02: 24, ASI03: 18, ASI04: 58, ASI05: 70, ASI06: 34, ASI07: 62, ASI08: 22, ASI09: 30, ASI10: 28 },
  },
  {
    id: "treasury-reconciler",
    name: "Treasury Reconciler",
    department: "Finance",
    owner: "S. Vale",
    inServiceSince: "Dec 2025",
    accessExpires: "Dec 2026",
    autonomy: "threshold",
    canMoveMoney: true,
    access: [
      { name: "Bank statements", mode: "read" },
      { name: "Ledger", mode: "write" },
      { name: "Banking portal", mode: "irreversible" },
      { name: "Payment rails", mode: "irreversible" },
    ],
    tools: [
      { name: "read_ledger", mode: "read" },
      { name: "reconcile", mode: "write" },
      { name: "move_funds", mode: "irreversible" },
    ],
    authority: 91,
    oversight: 61,
    posture: { ASI01: 46, ASI02: 52, ASI03: 56, ASI04: 64, ASI05: 82, ASI06: 50, ASI07: 72, ASI08: 44, ASI09: 46, ASI10: 58 },
  },
  {
    id: "supplier-screener",
    name: "Supplier Screener",
    department: "Procurement",
    owner: "J. Miles",
    inServiceSince: "May 2026",
    accessExpires: "May 2027",
    autonomy: "full-approval",
    canMoveMoney: false,
    access: [
      { name: "Supplier database", mode: "read" },
      { name: "Web search", mode: "read" },
      { name: "Risk scores", mode: "write" },
    ],
    tools: [
      { name: "search_web", mode: "read" },
      { name: "read_supplier", mode: "read" },
      { name: "score_risk", mode: "write" },
    ],
    authority: 29,
    oversight: 84,
    posture: { ASI01: 56, ASI02: 84, ASI03: 80, ASI04: 56, ASI05: 88, ASI06: 54, ASI07: 86, ASI08: 84, ASI09: 78, ASI10: 80 },
  },
  {
    id: "security-triage-agent",
    name: "Security Triage Agent",
    department: "Engineering",
    owner: "A. Bakker",
    inServiceSince: "Jul 2026",
    accessExpires: "Jul 2027",
    autonomy: "threshold",
    canMoveMoney: false,
    access: [
      { name: "SIEM", mode: "read" },
      { name: "Endpoint fleet", mode: "irreversible" },
      { name: "Firewall rules", mode: "irreversible" },
    ],
    tools: [
      { name: "read_alerts", mode: "read" },
      { name: "block_ip", mode: "irreversible" },
      { name: "isolate_host", mode: "irreversible" },
    ],
    authority: 79,
    oversight: 69,
    posture: { ASI01: 51, ASI02: 58, ASI03: 62, ASI04: 60, ASI05: 76, ASI06: 56, ASI07: 66, ASI08: 40, ASI09: 52, ASI10: 60 },
  },
  {
    id: "exec-briefing-agent",
    name: "Exec Briefing Agent",
    department: "People",
    owner: "M. Duarte",
    inServiceSince: "Mar 2026",
    accessExpires: null,
    autonomy: "none",
    canMoveMoney: false,
    access: [
      { name: "Email (all-company)", mode: "read" },
      { name: "Docs", mode: "read" },
      { name: "Slack", mode: "write" },
    ],
    tools: [
      { name: "read_email", mode: "read" },
      { name: "summarise", mode: "read" },
      { name: "post_slack", mode: "write" },
    ],
    authority: 44,
    oversight: 40,
    posture: { ASI01: 17, ASI02: 74, ASI03: 58, ASI04: 68, ASI05: 84, ASI06: 26, ASI07: 70, ASI08: 66, ASI09: 28, ASI10: 46 },
  },
  {
    id: "invoice-processor",
    name: "Invoice Processor",
    department: "Finance",
    owner: "J. Miles",
    inServiceSince: "Feb 2026",
    accessExpires: null,
    autonomy: "none",
    canMoveMoney: true,
    access: [
      { name: "Supplier email", mode: "read" },
      { name: "AP system", mode: "write" },
      { name: "Banking portal", mode: "irreversible" },
    ],
    tools: [
      { name: "read_inbox", mode: "read" },
      { name: "match_po", mode: "write" },
      { name: "pay_invoice", mode: "irreversible" },
    ],
    authority: 96,
    oversight: 14,
    posture: { ASI01: 17, ASI02: 22, ASI03: 26, ASI04: 54, ASI05: 74, ASI06: 20, ASI07: 60, ASI08: 24, ASI09: 16, ASI10: 22 },
  },
];

/** Recent behaviour worth a supervisor's attention, newest first. */
export const ACTIVITY: readonly ActivityEvent[] = [
  { agentId: "invoice-processor", asi: "ASI02", severity: "critical", age: "now", message: "Paid a supplier it has never paid before, outside working hours" },
  { agentId: "procurement-assistant", asi: "ASI01", severity: "critical", age: "4m", message: "Followed an instruction embedded in a supplier PDF" },
  { agentId: "dev-assistant", asi: "ASI04", severity: "warning", age: "11m", message: "Loaded a connector published 3 days ago and never reviewed" },
  { agentId: "exec-briefing-agent", asi: "ASI06", severity: "warning", age: "38m", message: "Wrote a memory from an unverified external thread" },
  { agentId: "it-provisioning-agent", asi: "ASI03", severity: "critical", age: "1h", message: "Granted itself a broader role than yesterday" },
  { agentId: "customer-support-bot", asi: "ASI02", severity: "warning", age: "1h", message: "Issued 11 refunds in 4 minutes" },
  { agentId: "treasury-reconciler", asi: "ASI09", severity: "info", age: "2h", message: "Summary omitted 2 of the 9 transfers it executed" },
  { agentId: "campaign-writer", asi: "ASI02", severity: "info", age: "3h", message: "Raised an ad budget by 340% without a second approval" },
  { agentId: "security-triage-agent", asi: "ASI08", severity: "warning", age: "5h", message: "Isolated 6 hosts from a single low-confidence alert" },
  { agentId: "contract-reviewer", asi: "ASI07", severity: "info", age: "7h", message: "Accepted a task from an agent not on its allowlist" },
];

const BY_ID = new Map(AGENTS.map((a) => [a.id, a]));

/** Look up one agent, or undefined when the id is unknown. */
export function agentById(id: string): Agent | undefined {
  return BY_ID.get(id);
}
